Document environment variables
openstudiocoalition/openstudiocoalition.github.io pull request #2
Opened 2020-12-31 17:19 UTC by macumber

2021-01-04 09:46 UTC, jmarrec requested changes

2021-01-04 09:46 UTC, jmarrec commented on markdown_source/docs/reference/openstudio_application_interface.md
> +- `OPENSTUDIO_APPLICATION_START_TAB_INDEX`, if set to an integer the application opens the specified tab first { SITE = 0, SCHEDULES = 1, CONSTRUCTIONS = 2, LOADS = 3, SPACE_TYPES = 4, GEOMETRY = 5,
I'm worried about maintainability here, perhaps we should add a note saying your can reference the most up to date by looking at the enum VerticalTabID in OSDocument.hpp?

https://github.com/openstudiocoalition/OpenStudioApplication/blob/139696fd6ff217fd3bfac08aaba1de23d157e25d/src/openstudio_lib/OSDocument.hpp#L142-L159

2021-01-04 09:46 UTC, jmarrec commented on markdown_source/docs/reference/openstudio_application_interface.md
> +A variety of environment variables can be used to modify the OpenStudio Applicaton's operation.  Environment variables can be set on the command line for a specific session or stored permantently in
```suggestion
A variety of environment variables can be used to modify the OpenStudio Application's operation.  Environment variables can be set on the command line for a specific session or stored permanently in the advanced system settings on Windows or in your profile file (eg `~/.bashrc`) on Unix.
```

2021-01-04 09:47 UTC, jmarrec approved these changes

2021-01-04 09:48 UTC, jmarrec commented
All good, with one comment you may want to address (or not). Thanks for the documentation.

2021-11-26 17:48 UTC, macumber commented
Added to https://github.com/openstudiocoalition/openstudiocoalition.github.io/pull/4

2021-11-26 17:48 UTC, closed without merging